on:
  push:
    branches:
      - main

name: quarto-render-publish

permissions: 
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      R_VERSION: '4.5.1'
      CMDSTAN_VERSION: '2.37.0'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

        # I created this list of dependencies with {dockerfiler}, so it's 
        # probably overly ambitious in installing stuff that might already be 
        # in the runner image, but it works and it's better than playing 
        # whack-a-mole with GHA to find any missing dependencies, so whatever ü§∑‚Äç‚ôÇÔ∏è
        #
        # dock <- dockerfiler::dock_from_renv(
        #   "renv.lock",
        #   FROM = "rocker/r-ver", AS = "renv-base",
        #   repos = c(
        #     CRAN = "https://cran.rstudio.com/",
        #     Stan = "https://stan-dev.r-universe.dev",
        #     tinytable = "https://vincentarelbundock.r-universe.dev"
        #   ),
        #   use_pak = FALSE
        # )
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            make \
            pandoc \
            libicu-dev \
            libx11-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            zlib1g-dev \
            cmake \
            xz-utils \
            libfribidi-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libwebp-dev \
            libxml2-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
          # use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set CmdStan environment variables
        run: |
          echo "CMDSTAN_PATH=${HOME}/.cmdstan" >> $GITHUB_ENV
        shell: bash

      - name: Cache CmdStan build
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: cmdstan-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: |
            cmdstan-${{ runner.os }}-

      - name: Build CmdStan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(version = Sys.getenv("CMDSTAN_VERSION"), cores = 2)
        shell: Rscript {0}

      - name: Render and publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
